### ISSUE TITLE
another test： scheduler/test_event_source.py:44: AssertionError

### ISSUE THREAD

**Issue by bigbencat** [ZiaWang/jqtrade#2]

**Comment by ZiaWang** [comment]
@bigbencat  Hi 我这边使用最新jqtrade跑tests/scheduler/test_event_source.py::test_get_days这个测试用例是没问题的哦

我这边环境：
* py = 3.6.13
* jqtrade = master(bac4b724cee33658f90abaab4bdaa8fc33321188)

**Comment by bigbencat** [comment]
嗯我换了环境好了，谢谢。

**Comment by ZiaWang** [comment]
客气了
